version: '2'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:9090
  db:
    build: ./infra
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=devcamp
    ports:
      - 5432:5432
